#!/bin/bash


### default
## source
source "/_and/config/bwraplua/default/0_default"


### script
## variable
declare -g _gs_modebus_proxy="on"

## argument
declare -ga "_ga_args_bwraplyr2"
_ga_args_bwraplyr2=(
        ,v, ,r, ,y,
        ,re "02_lvl_testcli"
        ,o --ro-bind "/_and/config/execute/bashrc" "/_and/config/execute/bashrc"
        ,co "/_and/config/execute/bashrc"
)
#       #
declare -ga "_ga_args_dbusproxy"
_ga_args_dbusproxy=(
        --talk="org.kde.StatusNotifierWatcher"
)

## source
source "${_ES_bwraplua_conf}/default/1_source_bwraplyr2"

## loadover
_gF_loadover

