#!/bin/bash

_ga_args_bwraplua=(
        ,q, ,c, ,y,
        ,na "3_calibre"
        ,ex "calibre"
        ,re "03_lvl3_calibre"
        ,co "calibre"
        ,c ${@}
)
#       #
bwraplua.lua ${_ga_args_bwraplua[@]}

