#!/bin/bash

_ga_args_bwraplua=(
        ,q, ,c, ,y,
        ,na "3_vscodium"
        ,ex "codium"
        ,re "03_lvl3_vscodium"
        ,co "/usr/bin/codium"
        ,c ${@}
        ,c "--ozone-platform-hint=auto"
        ,c "--enable-wayland-ime"
        ,c "--verbose"
)
#       #
bwraplua.lua ${_ga_args_bwraplua[@]}

