#!/bin/bash

_ga_args_bwraplua=(
        ,q, ,c, ,y,
        ,na "3_elisa"
        ,ex "elisa"
        ,re "03_lvl4_elisa"
        ,co "/usr/bin/elisa"
        ,c ${@}
)
#       #
bwraplua.lua ${_ga_args_bwraplua[@]}

