#!/bin/bash

_ga_args_bwraplua=(
        ,q, ,c, ,y,
        ,na "3_firefox-esr"
        ,ex "firefox"
        ,re "03_lvl3_firefox"
        ,co "/usr/bin/firefox-esr"
        ,c ${@}
)
#       #
bwraplua.lua ${_ga_args_bwraplua[@]}

