#!/bin/bash

_ga_args_bwraplua=(
        ,q, ,c, ,y,
        ,na "3_goldendict"
        ,ex "goldendict"
        ,re "03_lvl3_goldendict"
        ,co "goldendict"
        ,c ${@}
)
#       #
bwraplua.lua ${_ga_args_bwraplua[@]}

