#!/bin/bash

_ga_args_bwraplua=(
        ,q, ,c, ,y,
        ,na "3_kdenlive"
        ,ex "kdenlive"
        ,re "03_lvl3_kdenlive"
        ,co "kdenlive"
        ,c ${@}
)
#       #
bwraplua.lua ${_ga_args_bwraplua[@]}

