#!/bin/bash

_ga_args_bwraplua=(
        ,q, ,c, ,y,
        ,na "3_keepassxc"
        ,ex "keepassxc"
        ,re "03_lvl3_keepassxc"
        ,co "/usr/bin/keepassxc"
        ,c ${@}
)
#       #
bwraplua.lua ${_ga_args_bwraplua[@]}

