#!/bin/bash

_ga_args_bwraplua=(
        ,q, ,c, ,y,
        ,na "3_krita"
        ,ex "krita"
        ,re "03_lvl3_krita"
        ,co "krita"
        ,c ${@}
)
#       #
bwraplua.lua ${_ga_args_bwraplua[@]}

