#!/bin/bash

_ga_args_bwraplua=(
        ,q, ,c, ,y,
        ,na "3_remmina"
        ,ex "remmina"
        ,re "03_lvl3_remmina"
        ,co "remmina"
        ,c ${@}
)
#       #
bwraplua.lua ${_ga_args_bwraplua[@]}

