#!/bin/bash

_ga_args_bwraplua=(
        ,q, ,c, ,y,
        ,na "3_syncthingtray"
        ,ex "syncthingtray"
        ,re "03_lvl4_syncthing"
        ,co "syncthingtray"
        ,c ${@}
)
#       #
bwraplua.lua ${_ga_args_bwraplua[@]}

