#!/bin/bash

_ga_args_bwraplua=(
        ,q, ,c, ,y,
        ,na "3_thunderbird"
        ,ex "thunderbird"
        ,re "03_lvl3_thunderbird"
        ,co "/usr/bin/thunderbird"
        ,c ${@}
)
#       #
bwraplua.lua ${_ga_args_bwraplua[@]}

