#!/bin/bash


## postload
# and
source "/_and/config/bash/bashrc_d/1_style.bashrc"
source "/_and/config/bash/bashrc_d/1_control.bashrc"
source "/_and/config/bash/bashrc_d/1_config.bashrc"
source "/_and/config/bash/bashrc_d/2_script.bashrc"
source "/_and/config/bash/bashrc_d/2_execute.bashrc"

# own
if [[ -r "/_end/${USER}/_0_config/bash/bashrc" ]] ; then
        source "/_end/${USER}/_0_config/bash/bashrc" ;
fi

