#!/bin/bash

## environment
declare -xr _ES_bwraplua_pack="/_and/program/bwraplua"
declare -xr _ES_bwraplua_conf="/_and/config/bwraplua"
declare -xr _ES_bwraplua_usrbin="/_and/program/bwraplua/_usr/bin/bwraplua.lua"

## source
source "${_ES_bwraplua_conf}/default/1_source_loadinit"

