#!/bin/bash


### display
## variable
declare -gi "_gi_display"
_gi_display="$(( "$('/usr/bin/id' -u)" + "11" ))"

## check
while true ; do
        if [[ "${_gi_display}" -lt "1" || "${_gi_display}" -gt "60000" ]] ; then
                _gF_inittool_notify "ERROR" "Unavailable number." ;
                exit 1 ;
        elif [[ "${DISPLAY}" == ":${_gi_display}" ]] ; then
                _gi_display="$(( "${_gi_display}" + "1"))" ;
        elif [[ -r "/tmp/.X11-unix/X${_gi_display}" ]] ; then
                _gi_display="$(( "${_gi_display}" + "1"))" ;
        elif [[ -r "/tmp/.X${_gi_display}-lock" ]] ; then
                _gi_display="$(( "${_gi_display}" + "1"))" ;
        else
                break ;
        fi
done

## variable
declare -x _es_display=":${_gi_display}"

