#!/bin/bash


### icewm
## flock
_gF_loadexec_lockw "_default" "xephyr"
_gF_loadexec_lockw "_default" "icewm"

## argument
declare -ga "_ga_args_icewmlyr2"
#       #
declare -ga "_ga_args_bwraplua"
_ga_args_bwraplua=(
        ,q, ,c, ,y,
        ,re "00_pre_lyr1"
        ,r "00_post_lyr1"
        ,o --setenv "_es_wmname" "${_es_display}#${_gs_0_exec}"
        ,co '/bin/bash'
        ,c "${_ES_bwraplua_conf}/default/3_icewm_lyr2"
        ,,n ${_ga_args_icewmlyr2[@]}
)

## execute
"${_ES_bwraplua_usrbin}" ${_ga_args_bwraplua[@]} &

## loadexec
_gF_loadexec_kill "Xephyr"
_gF_loadexec_kill "icewm"

## wait
'/usr/bin/sleep' "0.2s"

