#!/bin/bash


### display
## variable
declare -gi "_gi_display"
_gi_display="$(( "$('/usr/bin/id' -u)" - "11" ))"

## check
'/usr/bin/ss' -a "/tmp/.X11-unix/X${_gi_display}"
#       #
if [[ "${_gi_display}" -lt "1" || "${_gi_display}" -gt "60000" ]] ; then
        _gF_inittool_notify "ERROR" "Unavailable number." ;
        exit 1 ;
elif [[ "${DISPLAY}" == ":${_gi_display}" ]] ; then
        _gF_inittool_notify "ERROR" "Number is used." ;
        exit 1 ;
elif [[ -r "/tmp/.X${_gi_display}-lock" ]] ; then
        _gF_inittool_notify "ERROR" "Socket is locked." ;
        exit 1 ;
elif [[ "${?}" == "0" ]] ; then
        _gF_inittool_notify "ERROR" "Socket is used." ;
        exit 1 ;
else
        rm -f "/tmp/.X11-unix/X${_gi_display}" ;
fi

## variable
declare -x _es_display=":${_gi_display}"

