#!/bin/bash


### proc
## check
if [[ "$(realpath -e "/proc/1/exe")" != "/usr/bin/bwrap" ]] ; then
        _gF_inittool_notify "ERROR" "Not running in bwrap." ;
        exit 127 ;
fi


### _bwrap
## check
if [[ ! -d "/_bwrap/and" ]] ; then
        _gF_inittool_notify "ERROR" "/_bwrap/and does not exist." ;
        exit 1 ;
fi
#       #
if [[ ! -d "/_bwrap/own/${USER}" ]] ; then
        _gF_inittool_notify "ERROR" "/_bwrap/own/${USER} does not exist." ;
        exit 1 ;
fi

