#!/bin/bash


### flock
## variable
declare -g "_gs_moderun_type"
declare -g "_gs_moderun_lock"

## lock
if [[ "${_gs_moderun_lock}" == "only" && -n "${_gs_0_exec}" ]] ; then
        _gF_loadexec_locko "${_gs_moderun_type:?}" "${_gs_0_exec}" || exit ;
fi


### xdg-dbus-proxy
## variable
declare -g "_gs_modebus_proxy"

## dbusproxy
if [[ "${_gs_modebus_proxy}" == "on" ]] ; then
        '/bin/bash' "${_ES_bwraplua_conf}/default/1_fork_dbusproxy" ${_ga_args_dbusproxy[@]} ;
fi


### x11
## variable
declare -g "_gs_modex11_display"
declare -g "_gs_modex11_xserver"

## display
if [[ "${_gs_modex11_display}" == "space" ]] ; then
        source "${_ES_bwraplua_conf}/default/1_source_x11space" ;
elif [[ "${_gs_modex11_display}" == "share" ]] ; then
        source "${_ES_bwraplua_conf}/default/1_source_x11share" ;
fi

## xserver
if [[ "${_gs_modex11_xserver}" == "xephyr" ]] ; then
        source "${_ES_bwraplua_conf}/default/1_source_xephyr" ;
fi
