#!/bin/bash


### init
## variable
declare -gi _gi_display_bak="${DISPLAY##*":"}"
declare -g _gs_0_exec="${0##*"/"}"
declare -g "_gs_arg1_flatpak"

## argument
declare -ga "_ga_arg1_flatpak"
_ga_arg1_flatpak=(
        run
        --socket=x11
        --nofilesystem="/tmp/.X11-unix/X${_gi_display_bak}"
        --nofilesystem="/tmp/.${_gi_display_bak}-lock"
        ${_ga_args_flatpaklyr1[@]}
)

## mode
if [[ "${_gs_0_exec}" != "${_gs_execname}" ]] ; then
        '/usr/bin/flatpak' info -l "${_gs_0_exec}" || exit ;
        declare -g _gs_arg1_flatpak=${_ga_arg1_flatpak[@]} ;
elif [[ "${1#*"."}" != "${1##*"."}" ]] ; then
        declare -g _gs_0_exec="${1:?}" || exit ;
        shift 1 ;
        declare -g _gs_arg1_flatpak=${_ga_arg1_flatpak[@]} ;
else
        unset -v "_gs_0_exec"
fi


### addmode
## variable
declare -g _gs_moderun_type="flatplyr1"

## source
source "${_ES_bwraplua_conf}/default/1_source_addmode"


### flatpak
## variable
declare -x DISPLAY="${_es_display}"

## argument
declare -ga "_ga_args_flatpak"
_ga_args_flatpak=(
        ${_gs_arg1_flatpak}
        "${_gs_0_exec}"
        ${@}
)

## execute
'/usr/bin/flatpak' ${_ga_args_flatpak[@]}

