#!/bin/bash


### default
## source
source "/_and/config/bwraplua/default/0_default"


### script
## variable
declare -g _gs_confpath="${_ES_bwraplua_conf}/execute/"
declare -g _gs_execname="2_bwraplyr1_and"
#       #
if [[ "${0##*"/"}" == "bwraplyr1_and" ]] ; then
        declare -g _gs_execname="bwraplyr1_and" ;
elif [[ "${0##*"/"}" == "bwraplyr1" ]] ; then
        declare -g _gs_execname="bwraplyr1" ;
else
        declare -g _gs_execname="2_bwraplyr1_and" ;
fi

## source
source "${_ES_bwraplua_conf}/default/1_source_bwraplyr1"

## loadover
_gF_loadover

