#!/bin/bash

## variable
declare -g _gs_confpath="/_end/${USER}/_0_config/bwraplua/execute/"
declare -g _gs_execname="2_bwraplyr1_own"

## check
if [[ "${0##*/}" == "bwraplyr1_own" ]] ; then
        declare -g _gs_execname="bwraplyr1_own" ;
fi

## argument
declare -a "_ga_args_bwraplyr1"

## source
source "/_and/config/bwraplua/default/1_source_bwraplyr1"

