#!/bin/bash


### init
## environment
test -d "${_eS_bwraplua_source}" -a -r "${_eS_bwraplua_source}" || exit

## source
source "${_eS_bwraplua_source}/0_init_set" || exit
source "${_eS_bwraplua_source}/../../etc/0_init_env" || exit
source "${_eS_bwraplua_source}/0_init_var" || exit
source "${_eS_bwraplua_source}/0_init_fun" || exit

