#!/bin/bash


### mkdir
## execute
mkdir "/_bwrap/own/${USER}/dbusproxy" || exit


### xdg-dbus-proxy
## argument
declare -a "_ga_args_xdgdbusproxy"
_ga_args_xdgdbusproxy=(
        ${DBUS_SESSION_BUS_ADDRESS}
        "/_bwrap/own/${USER}/dbusproxy/bus"
        --filter
        --log
        ${@}
)

## execute
"/usr/bin/xdg-dbus-proxy" ${_ga_args_xdgdbusproxy[@]} &


### while
## execute
while [[ -r "/_bwrap/own/${USER}/dbusproxy/bus" ]] ; do
        sleep "0.2s" ;
done

