#!/bin/bash


### proc
## check
if [[ "$(realpath -e "/proc/1/exe")" != "/usr/bin/bwrap" ]] ; then
        echo -e "\033[31m ERROR: Not running in bwrap. \033[0m" ;
        exit 127 ;
fi


### _bwrap
## check
if [[ ! -d "/_bwrap/and" ]] ; then
        echo -e "\033[33m WARNING: /_bwrap/and does not exist. \033[0m" ;
        exit 1 ;
fi
#       #
if [[ ! -d "/_bwrap/own/${USER}" ]] ; then
        echo -e "\033[33m WARNING: /_bwrap/own/${USER} does not exist. \033[0m" ;
        exit 1 ;
fi

