#!/bin/bash


### init
## environment
declare -gxr _eS_bwraplua_program="/_and/program/bwraplua"
declare -gxr _eS_bwraplua_package="/_and/program/bwraplua/_usr/bin/bwraplua.lua"
declare -gxr _eS_bwraplua_config="/_and/config/bwraplua"
declare -gxr _eS_bwraplua_data="/_and/data/bwrap"

