#!/bin/bash


### load
## function
function _eF_load_roomCall () 
{
        ## require
        _eF_load_initRequireVars "_es_loadExec_name" ;
        _eF_load_initRequireVars "_es_loadExec_type" ;
        ## export
        declare -gx _es_loadRoom_home="${_eS_bwraplua_runtime}/room" ;
        declare -gx _es_loadRoom_sort="${_es_loadRoom_home}/${_es_loadExec_type}" ;
        declare -gx _es_loadRoom_preset="${_es_loadRoom_preset:-"temp"}" ;
        declare -gx _es_loadRoom_create="${_es_loadRoom_create:-"mkdir"}" ;
        ## variable
        declare -i _li_stat="0" ;
        ## select
        case "${_es_loadRoom_preset}" in
                "name")
                        _eF_load_roomPresetName ;
                        ;;
                "temp")
                        _eF_load_roomPresetTemp ;
                        ;;
                *)
                        declare -i _li_stat="1" ;
                        ;;
        esac
        #       #
        case "${_es_loadRoom_create}" in
                "remove")
                        _eF_load_roomDeleteRemove ;
                        _eF_load_roomCreateMkdir ;
                        ;;
                "trash")
                        _eF_load_roomDeleteTrash ;
                        _eF_load_roomCreateMkdir ;
                        ;;
                "mkdir")
                        _eF_load_roomCreateMkdir ;
                        ;;
                *)
                        declare -i _li_stat="1" ;
                        ;;
        esac
        ## return
        return "${_li_stat}" ;
}
declare -fgxr "_eF_load_roomCall"
#       #
function _eF_load_roomPresetName () 
{
        ## require
        _eF_load_initRequireVars "_es_loadRoom_sort" ;
        _eF_load_initRequireVars "_es_loadExec_name" ;
        ## export
        declare -gx _es_loadRoom_dirs="${_es_loadRoom_sort}/${_es_loadRoom_name}" ;
}
declare -fxr "_eF_load_roomPresetName"
#       #
function _eF_load_roomPresetTemp () 
{
        ## require
        _eF_load_initRequireVars "_es_loadRoom_sort" ;
        _eF_load_initRequireVars "_es_loadExec_name" ;
        _eF_load_initRequirePath "/usr/bin/mktemp" ;
        ## export
        declare -gx "_es_loadRoom_dirs" ;
        ## common
        declare -a "_la_args_mktemp" ;
        _la_args_mktemp=(
                -u
                -d
                -p "${_es_loadRoom_sort}"
                -t "${_es_loadExec_name}_XXXXXXXX"
        )
        #       #
        _es_loadRoom_dirs="$('/usr/bin/mktemp' ${_la_args_mktemp[@]})" ;
}
declare -fxr "_eF_load_roomPresetTemp"
#       #
function _eF_load_roomCreateMkdir () 
{
        ## require
        _eF_load_initRequireVars "_es_loadRoom_dirs" ;
        ## common
        '/usr/bin/mkdir' -pv "${_es_loadRoom_dirs}" ;
        _eF_load_initExitno "${?}" "ERROR" "Room mkdir failure."
}
declare -fxr "_eF_load_roomCreateMkdir"
#       #
function _eF_load_roomDeleteRemove () 
{
        ## require
        _eF_load_initRequireVars "_es_loadRoom_sort" ;
        _eF_load_initRequireVars "_es_loadExec_name" ;
        _eF_load_initRequirePath "/usr/bin/rm" ;
        ## export
        declare -gx _es_loadRoom_dirs="${_es_loadRoom_sort}/${_es_loadRoom_name}" ;
        ## common
        '/usr/bin/rm' -rv "${_es_loadRoom_dirs}" ;
        #       #
        _eF_load_initInfops "set" "rm" ;
        _eF_load_initExitno "${_gi_stat_rm}" "ERROR" "Room remove failure." ;
        _eF_load_taskSet "loadRoom_delete" "${_gi_proc_rm}" ;
        _eF_load_initInfops "cut" "rm" ;
}
#       #
function _eF_load_roomDeleteTrash () 
{
        ## require
        _eF_load_initRequireVars "_es_loadRoom_sort" ;
        _eF_load_initRequireVars "_es_loadExec_name" ;
        _eF_load_initRequirePath "/usr/bin/trash-put" ;
        ## export
        declare -gx _es_loadRoom_dirs="${_es_loadRoom_sort}/${_es_loadRoom_name}" ;
        ## common
        '/usr/bin/trash-put' -v "${_es_loadRoom_dirs}" ;
        #       #
        _eF_load_initInfops "set" "trash" ;
        _eF_load_initExitno "${_gi_stat_trash}" "ERROR" "Room trash failure."_ ;
        _eF_load_taskSet "loadRoom_delete" "${_gi_proc_trash}" ;
        _eF_load_initInfops "cut" "trash" ;
}
declare -fgxr "_eF_load_roomDeleteTrash"

