#!/bin/bash

_ga_args_bwraplua=(
        ,,m
        ,q, ,c, ,y,
        ,na
        ,ex
        ,re
        ,r
        ,u
        ,i
        ,op
        ,o
        ,co
        ,c
        ,c ${@}
)
#       #
bwraplua.lua ${_ga_args_bwraplua[@]}

